# Generated by Django 4.2.20 on 2026-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='dimensions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
