# Generated by Django 4.2.20 on 2026-06-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_analysis', '0007_analysis_partial_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analysis',
            new_name='analysis_project_718154_idx',
            old_name='analysis_project_created_idx',
        ),
        migrations.RenameIndex(
            model_name='analysis',
            new_name='analysis_user_id_a30a3f_idx',
            old_name='analysis_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='analysis',
            new_name='analysis_type_fd7a52_idx',
            old_name='analysis_type_created_idx',
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['project', 'display_number'], name='analysis_project_d78eff_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['project', 'display_number'], name='insights_project_ece516_idx'),
        ),
    ]
