# Generated by Django 4.2.20 on 2026-06-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_uq_billing_profile_org'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagerecord',
            new_name='billing_usa_organiz_92eefa_idx',
            old_name='billing_usa_organiz_2c7a8f_idx',
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['organization_id'], name='billing_pro_organiz_1ec0c1_idx'),
        ),
    ]
