# Generated by Django 4.2.20 on 2026-07-29 08:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_reconcile_index_drift'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('project_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('provider', models.CharField(db_index=True, default='azure_openai', max_length=32)),
                ('model', models.CharField(db_index=True, help_text='Model or Azure deployment name as sent to the API.', max_length=128)),
                ('task_type', models.CharField(blank=True, db_index=True, default='', help_text='narration | aspect_classification | v2_workitems_experiment | ...', max_length=64)),
                ('call_count', models.PositiveIntegerField(default=1, help_text='LLM API calls represented by this row (>1 for batched fan-out).')),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveBigIntegerField(blank=True, help_text='Subset of output_tokens (o-series / GPT-5 reasoning). Not billed separately.', null=True)),
                ('cached_input_tokens', models.PositiveBigIntegerField(blank=True, help_text='Subset of input_tokens served from the prompt cache at a discounted rate.', null=True)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('input_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('output_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('pricing_version', models.CharField(blank=True, default='', max_length=32)),
                ('input_price_per_1k', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('output_price_per_1k', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('cached_input_price_per_1k', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('priced', models.BooleanField(db_index=True, default=False, help_text='False when the model had no price entry: tokens are real, cost is unknown (NULL).')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('analysis_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'billing_llm_usage_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'created_at'], name='llmusage_org_created_idx'), models.Index(fields=['project_id', 'created_at'], name='llmusage_proj_created_idx'), models.Index(fields=['user_id', 'created_at'], name='llmusage_user_created_idx'), models.Index(fields=['model', 'created_at'], name='llmusage_model_created_idx'), models.Index(fields=['task_type', 'created_at'], name='llmusage_task_created_idx'), models.Index(fields=['analysis_id'], name='llmusage_analysis_idx')],
            },
        ),
    ]
