# Generated by Django 4.2.20 on 2026-06-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_asana_task_mapping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='organizatio_organiz_2a0909_idx',
            old_name='organizatio_organiz_invite_status_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='organizatio_email_35a01b_idx',
            old_name='organizatio_email_invite_status_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='organizatio_expires_d4f028_idx',
            old_name='organizatio_invite_expires_idx',
        ),
    ]
