# Generated by Django 4.2.20 on 2026-07-12 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_registrationotp'),
        ('integrations', '0008_reconcile_index_drift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLastViewed',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(default=integrations.models._gen_view_id, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed_records', to='integrations.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_last_viewed', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'project_last_viewed',
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='project_las_user_id_d53817_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectlastviewed',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uq_project_user_last_viewed'),
        ),
    ]
